events {  }

http {
    server {
        listen 8000;
        location / {
            proxy_pass http://trust-anchor.org:8000;
        }
    }

    server {
        listen 8002;
        location / {
            proxy_pass http://cie-provider.org:8002;
            #proxy_bind $remote_addr transparent;
        }
    }

    server {
        listen 3000;
        location / {
            proxy_pass http://burpsuite:3000;
        }
    }

    server {
       listen 8080;
       location / {
         proxy_pass http://aac-provider.org:8080;
         proxy_set_header Host $host;
         proxy_set_header X-Real-IP $remote_addr;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Forwarded-Proto $scheme;
       }
     }

}


